---
title: "Untitled"
author: "varios"
date: "23/11/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(scipen = 999)
library(lifecontingencies)
library(tidyverse)
library(lubridate)
library(readxl)
library(kableExtra)
library(xtable)
library(stringr)
library(xts)
library(tinytex)


Afiliados_31_12_2020 <- read_excel("Afiliados_31_12_2020.xlsx")
Pensionados_31_12_2020 <- read_excel("Pensionados_31_12_2020.xlsx")
tabla_mortalidad_mujeres<-read_excel("tabla_mortalidad_mujeres.xlsx")
tabla_mortalidad_hombres<-read_excel("tabla_mortalidad_hombres.xlsx")



TablaDinamica_lxsHombres <- as.data.frame(read_excel("TablaDinamica-lxs.xls", 
    sheet = "Hombres"))
TablaDinamica_lxsMujeres <- as.data.frame(read_excel("TablaDinamica-lxs.xls", 
    sheet = "Mujeres"))





#Se genera lista con las tablas de los hombres

ListaDeTablasHombres <- list()


for (j in 1:(length(TablaDinamica_lxsHombres)-1)){
    
    ListaDeTablasHombres[[j]] <- with(TablaDinamica_lxsHombres,
                       new(
                         "actuarialtable",
                         interest = 0.06,
                         x = TablaDinamica_lxsHombres[,1],
                         lx = TablaDinamica_lxsHombres[,j+1] ,
                         name = paste("E",(j-1), sep = "")
                       ))
}
names(ListaDeTablasHombres)<-paste("E",seq(0,115), sep = "")


#Se genera lista con las tablas de las mujeres

ListaDeTablasMujeres <- list()
for (j in 1:(length(TablaDinamica_lxsMujeres)-1)){
    
    ListaDeTablasMujeres[[j]] <- with(TablaDinamica_lxsMujeres,
                       new(
                         "actuarialtable",
                         interest = 0.06,
                         x = TablaDinamica_lxsMujeres[,1],
                         lx = TablaDinamica_lxsMujeres[,j+1] ,
                         name = paste("E",(j-1), sep = "")
                       ))
}
names(ListaDeTablasMujeres)<-paste("E",seq(0,115), sep = "")

#Se elimina las tablas lm

#rm(TablaDinamica_lxsMujeres,TablaDinamica_lxsHombres )

#Se calcula la edad cumplida de la personas
dia_de_evaluacion<-as.Date('31/12/2020',format='%d/%m/%Y')

edad<-floor(time_length(difftime(
    dia_de_evaluacion,
    as.Date(as.POSIXct(Afiliados_31_12_2020$FEC_NACIMIENTO),'UTC')),'years'))

Afiliados_31_12_2020<-Afiliados_31_12_2020%>%mutate(FEC_INGRESO=paste(substr(FEC_INGRESO,1,4),
                    '/',substr(FEC_INGRESO,5,6),'/',substr(FEC_INGRESO,7,8),sep=''))

antiguedad<-time_length(difftime(
            dia_de_evaluacion,
            as.Date(Afiliados_31_12_2020$FEC_INGRESO,
            '%Y/%m/%d')),
            'years')
Afiliados_31_12_2020<-Afiliados_31_12_2020%>%mutate('Edad'=edad,'Antiguedad'=antiguedad)
#Se calcula edad de los pensionados
Pensionados_31_12_2020<-Pensionados_31_12_2020%>%mutate(FEC_NAC=paste(substr(FEC_NAC,1,4),
                    '/',substr(FEC_NAC,5,6),'/',substr(FEC_NAC,7,8),sep=''))
Pensionados_31_12_2020<-Pensionados_31_12_2020%>%mutate(FEC_RIG_PEN=paste(substr(FEC_RIG_PEN,1,4),
                    '/',substr(FEC_RIG_PEN,5,6),'/',substr(FEC_RIG_PEN,7,8),sep=''))
edad<-floor(time_length(difftime(
            dia_de_evaluacion,
            as.Date(Pensionados_31_12_2020$FEC_NAC,
            '%Y/%m/%d')),
            'years'))
tiempo_pension<-floor(time_length(difftime(
            dia_de_evaluacion,
            as.Date(Pensionados_31_12_2020$FEC_RIG_PEN,
            '%Y/%m/%d')),
            'years'))

Pensionados_31_12_2020<-Pensionados_31_12_2020%>%mutate('Edad'=edad,'T_Pension'=tiempo_pension)

#se crean bases de datos según genero
afil_hombres <- Afiliados_31_12_2020 %>% filter(SEXO == "M")
pen_hombres <- Pensionados_31_12_2020 %>% filter(SEX == "M")
afil_mujeres <- Afiliados_31_12_2020 %>% filter(SEXO == "F")
pen_mujeres <- Pensionados_31_12_2020 %>% filter(SEX == "F")


```




## Analisis estadistico
```{r}
Afiliados_31_12_2020 <- read_excel("Afiliados_31_12_2020.xlsx") %>%
  mutate(FEC_NACIMIENTO = ymd(FEC_NACIMIENTO),
         edad = floor(lubridate::time_length(difftime(today(), FEC_NACIMIENTO), "years")))

Pensionados_31_12_2020 <- read_excel("Pensionados_31_12_2020.xlsx") %>%
  mutate(FEC_NAC = ymd(FEC_NAC),
         edad = floor(lubridate::time_length(difftime(today(), FEC_NAC), "years")))
Pensionados_31_12_2020
```


```{r}
tblPrint <- function(tbl, cap = NULL){
    tbl %>%  kbl(caption = cap) %>%
  kable_styling(bootstrap_options = c("striped", "condensed"),
                latex_options = "HOLD_position",
                full_width = F)
}


summary(Afiliados_31_12_2020) %>% tibble() %>%  zoo::na.fill(fill = "") %>% tblPrint("Afiliados")

summary(Pensionados_31_12_2020) %>% tibble() %>%  zoo::na.fill(fill = "") %>% tblPrint("Pensionados")
```

```{r}
afi <- Afiliados_31_12_2020 %>% mutate(
  SEXO = as.factor(SEXO),
  edad = as.factor(edad)
)

pobAfi <- afi %>% group_by(edad, SEXO)%>%
  summarize(Cantidad =  n())

n <- sum(pobAfi$Cantidad[pobAfi$SEXO=="M"])
m <- sum(pobAfi$Cantidad[pobAfi$SEXO=="F"])


pobAfi$Cantidad[pobAfi$SEXO == "M"] <- -pobAfi$Cantidad

pobAfi$Cantidad[pobAfi$SEXO=="M"] <-
                pobAfi$Cantidad[pobAfi$SEXO=="M"]/n
pobAfi$Cantidad[pobAfi$SEXO=="F"] <-
                pobAfi$Cantidad[pobAfi$SEXO=="F"]/m
colnames(pobAfi)[3] <- "Porcentaje"

pobAfi %>% ggplot(aes(x=edad, y=Porcentaje, fill=SEXO)) +
  geom_bar(stat="identity") +
  coord_flip()+
  theme_minimal()+labs(title="Afiliados 31 de diciembre 2020")
```




```{r}
pen <- Pensionados_31_12_2020 %>% mutate(
  SEXO = as.factor(SEX),
  edad = as.factor(edad)
)

pobPen <- pen %>% group_by(edad, SEX)%>%
  summarize(Cantidad =  n())

n <- sum(pobPen$Cantidad[pobPen$SEX=="M"])
m <- sum(pobPen$Cantidad[pobPen$SEX=="F"])


pobPen$Cantidad[pobPen$SEX == "M"] <- -pobPen$Cantidad

pobPen$Cantidad[pobPen$SEX=="M"] <-
  pobPen$Cantidad[pobPen$SEX=="M"]/n
pobPen$Cantidad[pobPen$SEX=="F"] <-
  pobPen$Cantidad[pobPen$SEX=="F"]/m
colnames(pobPen)[3] <- "Porcentaje"

pobPen %>% ggplot(aes(x=edad, y=Porcentaje, fill=SEX)) +
  geom_bar(stat="identity") +
  coord_flip()+
  theme_minimal()+labs(title="Pensionados 31 de diciembre 2020")
```

















## Estocastico
```{r}
#La idea del codigo es basarse en el paradigma de divide y venceras
#Se procede a programar el modelo estocasticos
##Primero se procede a programar una funcion la cual determina
##la probabilidad de que la persona muera en ese año
##La idea sería ver cual es la probabilidad de que la persona
##en esa edad x se muera en ese mismo año, para pasar
##este parametro a otra funcion la cual simula si la persona
##muere o no
###Recibe la parámetros
###edad puede ser un vector
###ano este es el año en el que se quiere hacer la evaluacion
###tabla es la tabla de mortalidad, debe ser dinámica
###j tiempo posterior al año de partida
#qx<-function(edad,anho,tabla,tiempo,columna){
#  if(edad+2<nrow(tabla)){
#    prob_muerte<-1-tabla[edad+2,columna+2]/tabla[edad+1,columna+2]
#    }else{
#      prob_muerte<-1
#    }
#    return(as.numeric(prob_muerte))
#}

antiguedad<-function(n){
    return(c(
        (n>=10 & n<20)*0.45+ ##Rettonra el porcentaje de pension
        (n>=20 & n<30)*0.65+
        (n>=30 & n<40)*0.85+
        (n>=40),
        1+(n>=10 & n<20)+ #Retorna el monto lumpsum
        (n>=20 & n<30)*2+
        (n>=30 & n<40)*3+
        (n>=40)*4
        )
    )
}

#Se programa una funcion la cual se encarga de calcular el 
#monto de cada persona e irla sumando a la cantidad para ver
#costo de una simulación
#Se asume distribucion uniforma de muertes
#Aplicar la funcion para hombres y otra para 
#mujeres
#base_de_datos corresponde a la base de 
#afiliados la cual se otoroga
#t_descuento corresponde a la tasa nominal de 
#de descuento
#inflacion es la inflacion 
#La jubilacion va por persona
#A pesar de que esto es el seguro de costos 
#funerarios, se programa una funcion a parte para la pension
seguro<-function(sex,base_de_datos,t_descuento,inflacion,aumento_real,jubilacion,simulaciones){
    edades<-base_de_datos$Edad 
    v<-1/(1+t_descuento)
    fn1<-function(edad){
        aux<-0
        simulacion<-simulaciones
        vivos<-0
        j<-1
        Edad<-edad
        while(simulacion>0 & edad<jubilacion){
          if(sex){
            probabilidad<-pxt(ListaDeTablasHombres[[(Edad+1)]], x=edad,t=1)
            vivos<-sum(rbinom(n=simulacion,size=1,prob=probabilidad))
            muertos<-simulacion-vivos
            aux<-aux+v^j*muertos
            simulacion<-vivos
            edad<-edad+1
            j<-j+1
        } else{
            probabilidad<-pxt(ListaDeTablasMujeres[[(Edad+1)]], x=edad,t=1)
            vivos<-sum(rbinom(n=simulacion,size=1,prob=probabilidad))
            muertos<-simulacion-vivos
            aux<-aux+v^j*muertos
            simulacion<-vivos
            edad<-edad+1
            j<-j+1
        }
    }
         suma<-aux*2000000
         aux<-0 
    while(simulacion>0){
          if(sex){
            probabilidad<-pxt(ListaDeTablasHombres[[(Edad+1)]], x=edad,t=1)
            vivos<-sum(rbinom(n=simulacion,size=1,prob=probabilidad))
            muertos<-simulacion-vivos
            aux<-aux+v^j*muertos
            simulacion<-vivos
            edad<-edad+1
            j<-j+1
        } else{
            probabilidad<-pxt(ListaDeTablasMujeres[[(Edad+1)]], x=edad,t=1)
            vivos<-sum(rbinom(n=simulacion,size=1,prob=probabilidad))
            muertos<-simulacion-vivos
            aux<-aux+v^j*muertos
            simulacion<-vivos
            edad<-edad+1
            j<-j+1
        }
    }
    aux<-aux*1000000
    suma<-suma+aux

    return(suma/simulaciones)
    }
    valores<-mapply(FUN=fn1,edad=edades)
    suma<-sum(valores)
    return(suma)
}

##Se procede a programar una funcion la cual permite calcular el monto de la pension
##la idea esta funcion es que la funcion costos_afiliados_envie la cantidad de la poblacion
##ha sobrevivido hasta el momento
##Se le deben pasar el parametro simulacion que indica la cantidad de sobrevivientes hasta
##ese momento
##El momento es el momento j
##El anhno tambien debe ser pasado, para poder ubicarse en la tabla de mortalidad
##Tambien se le deben pasar la inflacion y tambien tasa de descuento
pension_afil<-function(base_de_datos,sex,t_descuento,m,simulaciones,inflacion,aumento_real,jubilacion){
  v<-1/(1+t_descuento)
  aumento<-(1+0.03)*(1+aumento_real)
  edades<-base_de_datos$Edad
  antiguedades<-base_de_datos$Antiguedad
  montos<-base_de_datos$DEVENGADO
  fn2<-function(edad,monto,anti){
    Edad<-edad
    j<-1/m
    suma<-0
    simulacion<-simulaciones
    monto<-monto*(v*aumento)^(max(jubilacion-Edad,0))
    monto<-monto*(antiguedad(anti+max(jubilacion-Edad,0))[1])
    while(simulacion>0){
      if(sex){
        probabilidad<-pxt(ListaDeTablasHombres[[(Edad+1)]], x=edad,t=1/m)
      }else{
        probabilidad<-pxt(ListaDeTablasMujeres[[(Edad+1)]], x=edad,t=1/m)
      }
      vivos<-sum(rbinom(n=simulacion,size=1,prob=probabilidad))
      simulacion<-vivos
      edad<-edad+1/m
      suma<-suma+v^j*monto*vivos
      monto<-monto*(1+inflacion)^(floor(j)==j)
      j<-j+1/m
    }
    return(suma/simulaciones)
  }
  valores<-mapply(FUN=fn2,edad=edades,monto=montos,anti=antiguedades)
    return(sum(valores))
}
pension_pen<-function(base_de_datos,sex,t_descuento,m,simulaciones,inflacion,aumento_real,jubilacion){
  v<-1/(1+t_descuento)
  aumento<-(1+0.03)*(1+aumento_real)
  edades<-base_de_datos$Edad
  antiguedades<-0
  montos<-base_de_datos$MON_PENSION
  fn2<-function(edad,monto,anti){
    Edad<-edad
    j<-1/m
    suma<-0
    simulacion<-simulaciones
    monto<-monto*(v*aumento)^(max(jubilacion-Edad,0))
    monto<-monto
    while(simulacion>0){
      if(sex){
        probabilidad<-pxt(ListaDeTablasHombres[[(Edad+1)]], x=edad,t=1/m)
      }else{
        probabilidad<-pxt(ListaDeTablasMujeres[[(Edad+1)]], x=edad,t=1/m)
      }
      vivos<-sum(rbinom(n=simulacion,size=1,prob=probabilidad))
      simulacion<-vivos
      edad<-edad+1/m
      suma<-suma+v^j*monto*vivos
      monto<-monto*(1+inflacion)^(floor(j)==j)
      j<-j+1/m
    }
    return(suma/simulaciones)
  }
  valores<-mapply(FUN=fn2,edad=edades,monto=montos,anti=antiguedades)
    return(sum(valores))
}
#Funcion para calculo de lump sum
lump_sum_st<-function(base_de_datos,t_descuento,simulaciones,inflacion,aumento_real,jubilacion){
  edades<-base_de_datos$Edad
  monto<-base_de_datos$DEVENGADO
  sexo<-base_de_datos$SEXO
  Antiguedades<-base_de_datos$Antiguedad
  aumento<-(1+inflacion)*(1+aumento_real)
  v<-1/(1+t_descuento)
  fn3<-function(edad,monto,sexo,anti){
    simulacion<-simulaciones
    Edad<-edad
    while(simulacion>0 & edad<jubilacion){
      if(sexo=='M'){
        probabilidad<-pxt(ListaDeTablasHombres[[(Edad+1)]], x=edad,t=max(jubilacion-edad,0))
      }else{
        probabilidad<-pxt(ListaDeTablasMujeres[[(Edad+1)]], x=edad,t=max(jubilacion-edad,0))
      }
        simulacion<-sum(rbinom(n=simulacion,size=1,prob=probabilidad))
        edad<-edad+max(jubilacion-edad,0)
    }
    monto<-monto*(aumento)^(max(jubilacion-Edad,0))*antiguedad(anti+max(jubilacion-Edad,0))[2]
    monto<-monto*v^(max(jubilacion-Edad,0))
    return(simulacion*monto/simulaciones)
  }
  valores<-mapply(FUN=fn3,edad=edades,monto=monto,sexo=sexo,anti=Antiguedades)
  return(sum(valores))
}



```



```{r}
#A partir de lo anterior se procede a programar una funcion la cual 
#calcula el costo de la pension a apartir de las dos funciones anteriores
#debe recibir las dos bases de datos de afiliados y la base de pensionados
#y todos los parametros que recibe la pension de costo de afiliados

costo_plan<-function(t_descuento,inflacion,aumento_real,afiliados,pensionados,simulaciones,m){
    afil_mujeres<-afiliados%>%filter(SEXO=="F")
    afil_hombres<-afiliados%>%filter(SEXO=="M")
    pen_mujeres<-pensionados%>%filter(SEX=="F")
    pen_hombres<-pensionados%>%filter(SEX=="M")
    hombres_afil_lum<-lump_sum_st(afil_hombres,t_descuento,simulaciones,inflacion,aumento_real,65)
    hombres_afil_vida<-seguro(TRUE,afil_hombres,t_descuento,inflacion,aumento_real,65,simulaciones)
    hombres_afil_pen<-pension_afil(afil_hombres,TRUE,t_descuento,m,simulaciones,inflacion,aumento_real,65)
    mujeres_afil_lum<-lump_sum_st(afil_mujeres,t_descuento,simulaciones,inflacion,aumento_real,62)
    mujeres_afil_vida<-seguro(FALSE,afil_hombres,t_descuento,inflacion,aumento_real,65,simulaciones)
    mujeres_afil_pen<-pension_afil(afil_hombres,FALSE,t_descuento,m,simulaciones,inflacion,aumento_real,62)
    ##Pensionados
    hombres_pen_vida<-seguro(TRUE,pen_hombres,t_descuento,inflacion,aumento_real,65,simulaciones)
    hombres_pen_pen<-pension_pen(pen_hombres,TRUE,t_descuento,m,simulaciones,inflacion,aumento_real,65)
    mujeres_pen_vida<-seguro(FALSE,pen_mujeres,t_descuento,inflacion,aumento_real,65,simulaciones)
    mujeres_pen_pen<-pension_pen(pen_mujeres,FALSE,t_descuento,m,simulaciones,inflacion,aumento_real,62)
    
    return(hombres_afil_lum+hombres_afil_pen+hombres_afil_vida+hombres_pen_pen+hombres_pen_vida
    +mujeres_afil_lum+mujeres_afil_pen+mujeres_afil_vida+mujeres_pen_pen+mujeres_pen_vida
    )
}

```


```{r}
##Prueba de simulacion se ecirbe para evitar perdida de datos
# prueba<-Afiliados_31_12_2020[1,]


calculo_prueba<-costo_plan(t_descuento=0.06,inflacion=0.03,aumento_real=0.02,Afiliados_31_12_2020,Pensionados_31_12_2020,simulaciones=10,m=12)
write.table(calculo_prueba,file="prueba.txt",sep="")
```













## Deterministico



```{r}
# PensionMensualDeterministico
##No es un seguro de vida completo y necesita diferimiento
PensionMensualDeterministico <-
  function(Edad, hombre, antiguedad1, ultimo_salario, tasa_descuento, tasa_cre_salario) {
  
    #Considerando una inflacion del 3%
    tasa_cre_salario<-(1+tasa_cre_salario)*(1+0.03)
    v<-(1)/(1+tasa_descuento)
    
    #porcentaje de pensión
    porcentaje_de_pension <- function(antiguedad) {
      por<-c( (antiguedad >= 10 & antiguedad < 20) * 0.45 +
          (antiguedad >= 20 & antiguedad < 30) * 0.65 +
          (antiguedad >= 30 & antiguedad < 40) * 0.85 +
          (antiguedad >= 40)
      )
      
      if(antiguedad1==-1){
        por<-1
      }
      return(por)
    }
      
    #Ajustamos el salario
    ultimo_salario1<-ultimo_salario*(tasa_cre_salario*v)^(max(65-Edad,0))
    #Antiguedad al momento de pencionarse
    MontoAPagar<-porcentaje_de_pension(antiguedad1+max(65-Edad,0)) *ultimo_salario1
    if(hombre){
      if(antiguedad1==-1){
        survive<-1
        l<-Edad
      }else{
        survive<-pxt(ListaDeTablasHombres[[(Edad+1)]], x=Edad,t=max(65-Edad,0))
        l<-Edad
        Edad<-Edad+max(65-Edad,0)
      }
 
    #anualidad imnediata
    vectorMensual<-(seq(1/12, (115-Edad+1), 1/12))
    vectorAnualmensual<-sort(rep(c(0:(115-Edad)),12))
    anualidad <-pxt(ListaDeTablasHombres[[(l+1)]], x=Edad,t=vectorMensual )*(v)^(vectorMensual)
    #monto a pagar con ajuste inflacionario
    MontoAPagar <-MontoAPagar*(1+0.03)^(vectorAnualmensual)
    suma<-anualidad*MontoAPagar
    
    }else{
    #Ajustamos el salario
    ultimo_salario1<-ultimo_salario*(tasa_cre_salario*v)^(max(62-Edad,0))
    #Antiguedad al momento de pencionarse
    MontoAPagar<-porcentaje_de_pension(antiguedad1+ max(62-Edad,0)) *  ultimo_salario1
      if(antiguedad1==-1){
        survive<-1
        l<-Edad
      }else{
        survive<-pxt(ListaDeTablasMujeres[[(Edad+1)]], x=Edad,t=max(62-Edad,0))
        l<-Edad
        Edad<-Edad+max(62-Edad,0)
      }
 
    #anualidad imnediata
    vectorMensual<-(seq(1/12, (115-Edad+1), 1/12))
    vectorAnualmensual<-sort(rep(c(0:(115-Edad)),12))
    anualidad <-pxt(ListaDeTablasMujeres[[(l+1)]], x=Edad,t=vectorMensual )*(v)^(vectorMensual)
    #monto a pagar con ajuste inflacionario
    MontoAPagar <-MontoAPagar*(1+0.03)^(vectorAnualmensual)
    suma<-anualidad*MontoAPagar
    
    }
    suma<-sum(suma)
    
  
    return(suma*survive)
}
```




```{r}
#SumaDeRetiroDeterministico
SumaDeRetiroDeterministico <- function(antiguedad, hombre, Edad, ultimo_salario,tasa_descuento, tasa_cre_salario) {
  #Considerando la inflación
  tasa_cre_salario<-(1+tasa_cre_salario)*(1+0.03)
  #Multiplo de lumpsum
  Multiplo <- function(antiguedad) {
    return(c(1 + (antiguedad >= 10 & antiguedad < 20) +
               (antiguedad >= 20 & antiguedad < 30) * 2 +
               (antiguedad >= 30 & antiguedad < 40) * 3 +
               (antiguedad >= 40) * 4))
  }
   if (hombre) {
        ultimo_salario<-ultimo_salario*tasa_cre_salario^max(65-Edad,0)
        antiguedad<-antiguedad+max(65-Edad,0)
        Monto<-ultimo_salario * Multiplo(antiguedad)
        Monto<-Monto*(1+tasa_descuento)^min(Edad-65,0)
        Monto<-Monto*pxt(ListaDeTablasHombres[[(Edad+1)]], Edad,t=max(65-Edad,0))
    } else{
      ultimo_salario<-ultimo_salario*tasa_cre_salario^max(62-Edad,0)
      antiguedad<-antiguedad+(62-Edad)
      Monto<-ultimo_salario * Multiplo(antiguedad)
      Monto<-Monto*(1+tasa_descuento)^min(Edad-62,0)
      Monto<-Monto*pxt(ListaDeTablasMujeres[[(Edad+1)]], Edad,t=max(62-Edad,0))
    }
  return(Monto)
}
```


```{r}
#SeguroVidaDeterministico
SeguroVidaDeterministico <- function(Edad, hombre) {
  if (Edad >= 65 & hombre) {
    return(1000000 * Axn(ListaDeTablasHombres[[(Edad + 1)]], x = Edad))
  } else if (Edad >= 62 & !hombre) {
    return(1000000 * Axn(ListaDeTablasMujeres[[(Edad + 1)]], x = Edad))
  } else if (Edad < 65 & hombre) { 
    #diferido
    return(2000000 * Axn(ListaDeTablasHombres[[(Edad + 1)]], x = Edad, n=(65-Edad)) +  1000000 * Axn(ListaDeTablasHombres[[(Edad + 1)]], x = Edad, m=(65-Edad)))
  } else if (Edad < 62 & !hombre) {
    return(2000000 * Axn(ListaDeTablasMujeres[[(Edad + 1)]], x = Edad, n=(62-Edad)) +  1000000 * Axn(ListaDeTablasMujeres[[(Edad + 1)]], x = Edad, m=(62-Edad)))
  }
}
```














```{r}
#Costo deterministico
CalculosDeterministicos <- function(Descuento, aumentoSalarial) {
  
#hombres
#Calculo de PensionMensualDeterministico para hombres
MontoDePensionMensualParaHombresDeterministicoActivos <-
  mapply(
    PensionMensualDeterministico,
    afil_hombres$Edad,
    TRUE,
    afil_hombres$Antiguedad,
    afil_hombres$DEVENGADO,
    Descuento,
    aumentoSalarial
  )
#calculo de SeguroVida Deterministico para hombres
MontoDeSeguroVidaParaHombresDeterministicoActivos <-
  mapply(SeguroVidaDeterministico, afil_hombres$Edad, TRUE)
#calculo de Retiro Deterministico para los afiliados para hombres
MontoSumaDeRetiroHombresDeterministicoActivos <-
  mapply(
    SumaDeRetiroDeterministico,
    afil_hombres$Antiguedad,
    TRUE ,
    afil_hombres$Edad,
    afil_hombres$DEVENGADO,
    Descuento,
    aumentoSalarial
  )
#calculo de Seguro Vida Deterministico pensionados para hombres
MontoDeSeguroVidaParaHombresDeterministicoPensionados <-
  mapply(SeguroVidaDeterministico, pen_hombres$Edad, TRUE)
#calculo de pension para hombres pensionados
MontoDePensionMensualParaHombresDeterministicoPensionados <-
  mapply(
    PensionMensualDeterministico,
    pen_hombres$Edad,
    TRUE,-1,
    pen_hombres$MON_PENSION,
    Descuento,
    aumentoSalarial
  )
#Calculo para mujeres
#Calculo de PensionMensualDeterministico para mujeres
MontoDePensionMensualParaMujeresDeterministicoActivos <-
  mapply(
    PensionMensualDeterministico,
    afil_mujeres$Edad,
    FALSE,
    afil_mujeres$Antiguedad,
    afil_mujeres$DEVENGADO,
    Descuento,
    aumentoSalarial
  )
#calculo de SeguroVida Deterministico para mujeres
MontoDeSeguroVidaParaMujeresDeterministicoActivos <-
  mapply(SeguroVidaDeterministico, afil_mujeres$Edad, FALSE)
#calculo de Retiro Deterministico para los afiliados para mujeres
MontoSumaDeRetiroMujeresDeterministicoActivos <-
  mapply(
    SumaDeRetiroDeterministico,
    afil_mujeres$Antiguedad,
    FALSE ,
    afil_mujeres$Edad,
    afil_mujeres$DEVENGADO,
    Descuento,
    aumentoSalarial
  )

#calculo de Seguro Vida Deterministico pensionados para mujeres
MontoDeSeguroVidaParaMujeresDeterministicoPensionados <-
  mapply(SeguroVidaDeterministico, pen_mujeres$Edad, FALSE)
MontoDePensionMensualParaMujeresDeterministicoPensionados <-
  mapply(
    PensionMensualDeterministico,
    pen_mujeres$Edad,
    FALSE,-1,
    pen_mujeres$MON_PENSION,
    Descuento,
    aumentoSalarial
  )
TablamontosDeterministicos <-
  data.frame(
    "Monto"=c(
      "Lump Sum de hombres activos",
      "Seguro de vida para hombres activos",
      "Pension mensual para hombres activos",
      "Lump Sum de mujeres activas",
      "Seguro de vida para mujeres activas",
      "Pension mensual para mujeres activas",
      "Seguro de vida hombres pensionados",
      "Pension mensual para hombres Pensionados",
      "Seguro Vida para Mujeres pensionadas",
      "Pension mensual para mujeres pensionadas",
      "Total"
    ),
    "Deterministico"=c(
      sum(MontoSumaDeRetiroHombresDeterministicoActivos),
      sum(MontoDeSeguroVidaParaHombresDeterministicoActivos),
      sum(MontoDePensionMensualParaHombresDeterministicoActivos),
      sum(MontoSumaDeRetiroMujeresDeterministicoActivos),
      sum(MontoDeSeguroVidaParaMujeresDeterministicoActivos),
      sum(MontoDePensionMensualParaMujeresDeterministicoActivos),
      sum(MontoDeSeguroVidaParaHombresDeterministicoPensionados),
      sum(MontoDePensionMensualParaHombresDeterministicoPensionados),
      sum(MontoDeSeguroVidaParaMujeresDeterministicoPensionados),
      sum(MontoDePensionMensualParaMujeresDeterministicoPensionados),
      sum(
        MontoSumaDeRetiroHombresDeterministicoActivos,
        MontoDeSeguroVidaParaHombresDeterministicoActivos,
        MontoDePensionMensualParaHombresDeterministicoActivos,
        MontoSumaDeRetiroMujeresDeterministicoActivos,
        MontoDeSeguroVidaParaMujeresDeterministicoActivos,
        MontoDePensionMensualParaMujeresDeterministicoActivos,
        MontoDeSeguroVidaParaHombresDeterministicoPensionados,
        MontoDePensionMensualParaHombresDeterministicoPensionados,
        MontoDeSeguroVidaParaMujeresDeterministicoPensionados,
        MontoDePensionMensualParaMujeresDeterministicoPensionados
      )
    )
  )
return( TablamontosDeterministicos)
}




TablamontosDeterministicos<-CalculosDeterministicos(0.06504,0.02)






#TablamontosDeterministicos$Deterministico[11]*0.15 = 64619604215,
#430797361435





366177757220-TablamontosDeterministicos$Deterministico[11]

```



















Moises 


```{r}

##Análisis de Sensibilidad

#Algunos vectores iniciales necesarios

tasas <- c(seq(0.01,0.12,0.01))

salarios <- c(seq(0,0.12,0.01))

orden1 <- c(seq(2,24,2))

orden2 <- c(seq(2,26,2))
MontosDesc<-c()
MontosSal <- c()
CambioSal <- c()
CambioTasa <- c()


#Calculo de sensibilidad con respecto a la tasa
MontoM <- mapply(CalculosDeterministicos, tasas,0.02 )

for (i in orden1) {
  MontosDesc[i/2]<-MontoM[[i]][11]
}

Sensibilidadtasa <- data.frame(tasas,MontosDesc)


#Calculo de sensibilidad con respecto a los salarios

MontoSalario <- mapply(CalculosDeterministicos, 0.06,salarios )

for (i in orden2) {
  MontosSal[i/2]<-MontoSalario[[i]][11]
}



for (j in 1:11) {
  
  CambioTasa[j+1]<- (MontosDesc[j+1]-MontosDesc[j])/MontosDesc[j]
  
}
CambioTasa[1]=0


for (j in 1:12) {
  
  CambioSal[j+1]<- (MontosSal[j+1]-MontosSal[j])/MontosSal[j]
  
}
CambioSal[1]=0

#Reescalamiento de los montos antes de generar los gráficos y tablas
MontosSal2<- MontosSal/1000000
MontosDesc2 <- MontosDesc/1000000

#Generacion de las tablas con los cambios
SensibilidadSalario <- data.frame(salarios,MontosSal2,CambioSal)
colnames(SensibilidadSalario) <- c("Tasa de Salarios","Monto (Millones CRC)","Cambio")


Sensibilidadtasa <- data.frame(tasas,MontosDesc2,CambioTasa)
colnames(Sensibilidadtasa) <- c("Tasa de descuento","Monto (Millones CRC)","Cambio")

print(xtable(Sensibilidadtasa, type = "latex", tabular.environment="longtable"),include.rownames=FALSE, file = "TablaSensiblidadTasa.tex")

print(xtable(SensibilidadSalario, type = "latex", tabular.environment="longtable"),include.rownames=FALSE, file = "TablaSensiblidadSalario.tex")


#Graficos

#Grafico de las tasas de descuento

ggplot(Sensibilidadtasa)+geom_line(aes(tasas,MontosDesc2))+theme(panel.grid = element_blank(),panel.background = element_blank(),axis.line = element_line(colour = "black") )+scale_x_continuous(breaks = seq(0.01,0.12,0.01),labels=c(seq(0.01,0.12,0.01)), limits = c(0.01,0.13))+labs(y = "Costo",
       x = "Tasas de descuento",
       title = "Sensibilidad del costo a distintas tasas de descuento")+theme(plot.title = element_text(hjust = .5),plot.caption = element_text(hjust = 0))+theme_minimal()


#Grafico del crecimiento de los salarios
ggplot(SensibilidadSalario)+geom_line(aes(salarios,MontosSal2))+theme(panel.grid = element_blank(),panel.background = element_blank(),axis.line = element_line(colour = "black") )+scale_x_continuous(breaks = seq(0,0.12,0.01),labels=c(seq(0,0.12,0.01)), limits = c(0,0.13))+labs(y = "Costo",
       x = "Tasa de crecimiento de salarios",
       title = "Sensibilidad del costo a distintas tasas de crecimiento de salarios")+theme(plot.title = element_text(hjust = .5),plot.caption = element_text(hjust = 0))+theme_minimal()


#Cambio

```





















